--COUNT NUMBER OF EQUIPMENT AT EACH WORKSITE, AND IF THE WORKSITE HAS LESS THAN TWO EQUIPMENT, FIND AND EQUIPMENT THAT IS NOT BEING USED AND ADD IT TO THE WORKSITE
CREATE OR REPLACE PROCEDURE NUM_EQUIPMENT (
    p_EquimentID IN Equipment.EquimentID%type,
    p_NumEquipment OUT NUMBER,
    p_SumPrice OUT NUMBER
)
IS 
BEGIN 
SELECT COUNT(EQUIPMENTID), COUNT(EQUIPMENTID), SUM(EquipmentPurchasePrice) INTO p_SumPrice